route:
  receiver: 'rocketchat'

  
receivers:
- name: "rocketchat"
  webhook_configs:
  - url: 'http://rocketchat:3000/hooks/4FZpLyoTHQJM5eiho/ueBAYY2zyWwCfpPGA68G5qBpjjawkKa5GfntNwgaoYT2oQpW'
    send_resolved: true
            
